services:
  - type: web
    name: playto-community-feed
    env: python
    buildCommand: "pip install -r requirements.txt && python manage.py migrate"
    startCommand: "gunicorn config.wsgi:application"
    rootDir: backend
